# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainScreen.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from Spell_Grammer_Check import Ui_MainWindow1
from IMAGE_TO_TEXT import  Ui_MainWindow2
from ParaphraseScreen import Ui_MainWindow3
from SummaryScreen import Ui_SummaryWindow4


class Ui_MainWindow(object):
    def Spell_Grammer_Check2(self):
        self.window1 = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow1()
        self.ui.setupUi(self.window1)
        self.window1.show()
    def IMAGE_TO_TEXT(self):
        self.window1 = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow2()
        self.ui.setupUi(self.window1)
        self.window1.show()
    def ParaphraseScreen1(self):
        self.window1 = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow3()
        self.ui.setupUi(self.window1)
        self.window1.show()
    def summaryui3(self):
        self.window1 = QtWidgets.QMainWindow()
        self.ui = Ui_SummaryWindow4()
        self.ui.setupUi(self.window1)
        self.window1.show()      
    def ImagebasicFuncs(self):
            self.pushButton.setVisible(False)
            self.pushButton_2.setVisible(False)
            self.pushButton_4.setVisible(False)
            self.label_4.setVisible(False)
            self.label_5.setVisible(False)
            self.label_9.setVisible(False)
            self.label_8.setVisible(True)
            self.pushButton_3.setVisible(True)
    def ParabasicFuncs(self):
            self.pushButton.setVisible(True)
            self.pushButton_2.setVisible(True)
            self.pushButton_4.setVisible(True)
            self.pushButton_3.setVisible(False)
            self.label_4.setVisible(True)
            self.label_5.setVisible(True)
            self.label_9.setVisible(True)
            self.label_8.setVisible(False)

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(833, 423)
        MainWindow.setStyleSheet("background-color: #272743")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(380, 20, 111, 20))
        self.label.setStyleSheet("color:rgb(255, 255, 253);\n"
"\n"
"font: SMILEN;\n"
"\n"
"font-size: 15px;")
        self.label.setObjectName("label")
        self.textEdit_5 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_5.setGeometry(QtCore.QRect(10, 280, 281, 131))
        self.textEdit_5.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.textEdit_5.setObjectName("textEdit_5")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 250, 71, 20))
        self.label_2.setStyleSheet("color:rgb(255, 255, 253);\n"
"\n"
"font: Smilen;\n"
"\n"
"font-size:14pt;")
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(390, 130, 421, 71))
        self.pushButton.setStyleSheet("background-color: rgb(186, 232, 232);\n"
"color: rgb(45, 102, 142);\n"
"font: SMILEN;\n"
"font-size: 14pt;")
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.Spell_Grammer_Check2)
        # self.pushButton.setVisible(False)
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(390, 210, 421, 71))
        self.pushButton_2.setStyleSheet("background-color: rgb(186, 232, 232);\n"
"color: rgb(45, 102, 142);\n"
"font: SMILEN;\n"
"font-size: 14pt;")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.clicked.connect(self.ParaphraseScreen1)
        # self.pushButton_2.setVisible(False)
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(390, 50, 421, 71))
        self.pushButton_3.setStyleSheet("background-color: rgb(186, 232, 232);\n"
"color: rgb(45, 102, 142);\n"
"font: SMILEN;\n"
"font-size: 14pt;")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_3.clicked.connect(self.IMAGE_TO_TEXT)
        # self.pushButton_3.setVisible(False)
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(390, 290, 421, 71))
        self.pushButton_4.setStyleSheet("background-color: rgb(186, 232, 232);\n"
"color: rgb(45, 102, 142);\n"
"font:\"SMILEN\";\n"
"font-size: 14pt;")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_4.clicked.connect(self.summaryui3)
        # self.pushButton_4.setVisible(False)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(50, 40, 171, 151))
        self.label_3.setStyleSheet("background-color: #272743")
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("LM.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(400, 140, 61, 51))
        self.label_4.setStyleSheet("background-color: rgb(186, 232, 232);")
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("Check grammar and spelling error.png"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        # self.label_4.setVisible(False)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(400, 220, 61, 51))
        self.label_5.setStyleSheet("background-color: rgb(186, 232, 232);")
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("Paraphrase Sentence.png"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        # self.label_5.setVisible(False)
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(400, 60, 61, 51))
        self.label_8.setStyleSheet("background-color: rgb(186, 232, 232);")
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap("Convert Image to Text.png"))
        self.label_8.setScaledContents(True)
        self.label_8.setObjectName("label_8")
        # self.label_8.setVisible(False)
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(400, 300, 61, 51))
        self.label_9.setStyleSheet("background-color: rgb(186, 232, 232);")
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap("Generate Summary.png"))
        self.label_9.setScaledContents(True)
        self.label_9.setObjectName("label_9")
        # self.label_9.setVisible(False)
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(420, 370, 101, 41))
        self.pushButton_5.setStyleSheet("background-color: rgb(186, 232, 232);\n"
"color: rgb(45, 102, 142);\n"
"font: SMILEN;\n"
"border-style:outset;\n"
"border-width:2px;\n"
"border-radius:10px;\n"
"font:bold 12px;\n"
"border-color:black;\n"
"padding:10px;")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_5.clicked.connect(self.ImagebasicFuncs)
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(570, 370, 101, 41))
        self.pushButton_6.setStyleSheet("background-color: rgb(186, 232, 232);\n"
"color: rgb(45, 102, 142);\n"
"font: SMILEN;\n"
"border-style:outset;\n"
"border-width:2px;\n"
"border-radius:10px;\n"
"font:bold 12px;\n"
"border-color:black;\n"
"padding:10px;")
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_6.clicked.connect(self.ParabasicFuncs)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "  GET STARTED"))
        self.textEdit_5.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; font-weight:600; color:#1d2035;\">LingMaster is a Desktop application that will provide assistance in the reading and writing of text documents written in English. It is designed and developed by the students of UIT as their final year project.</span></p></body></html>"))
        self.textEdit_5.setPlaceholderText(_translate("MainWindow", "Write your sentence here.."))
        self.label_2.setText(_translate("MainWindow", "ABOUT:"))
        self.pushButton.setToolTip(_translate("MainWindow", "<html><head/><body><p>hello</p></body></html>"))
        self.pushButton.setText(_translate("MainWindow", "     GRAMMAR AND SPELL CHECK"))
        self.pushButton_2.setText(_translate("MainWindow", "PARAPHRASING TEXT"))
        self.pushButton_3.setText(_translate("MainWindow", "    IMAGE TO TEXT CONVERTER"))
        self.pushButton_4.setText(_translate("MainWindow", "SUMMARY GENERATOR"))
        self.pushButton_5.setText(_translate("MainWindow", "Input Image"))
        self.pushButton_6.setText(_translate("MainWindow", "Input Text"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
