# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ParaphraseScreen.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox
from spinrewriterapi import SpinRewriterAPI
email_address = "abdulmannanibrahim67@gmail.com"
api_key = "d4f9b55#83c8f2f_7d9685b?4b3329f"


class Ui_MainWindow3(object):
    def Paraphrasingwork(self):
        spinrewriter_api = SpinRewriterAPI(email_address, api_key)
        # (optional) Set whether the One-Click Rewrite process automatically protects
        # Capitalized Words outside the article's title.
        spinrewriter_api.set_auto_protected_terms(False)

        # (optional) Set the confidence level of the One-Click Rewrite process.
        spinrewriter_api.set_confidence_level("medium")

        # (optional) Set whether the One-Click Rewrite process uses nested spinning syntax (multi-level spinning) or not.
        spinrewriter_api.set_nested_spintax(True)

        # (optional) Set whether Spin Rewriter rewrites complete sentences on its own.
        spinrewriter_api.set_auto_sentences(False)

        # (optional) Set whether Spin Rewriter rewrites entire paragraphs on its own.
        spinrewriter_api.set_auto_paragraphs(False)

        # (optional) Set whether Spin Rewriter writes additional paragraphs on its own.
        spinrewriter_api.set_auto_new_paragraphs(False)

        # (optional) Set whether Spin Rewriter changes the entire structure of phrases and sentences.
        spinrewriter_api.set_auto_sentence_trees(False)

        # (optional) Sets whether Spin Rewriter should only use synonyms (where available) when generating spun text.
        spinrewriter_api.set_use_only_synonyms(False)

        # (optional) Sets whether Spin Rewriter should intelligently randomize the order of paragraphs and lists when
        # generating spun text.
        spinrewriter_api.set_reorder_paragraphs(False)

        # (optional) Sets whether Spin Rewriter should automatically enrich generated articles with headings, bulpoints, etc.
        spinrewriter_api.set_add_html_markup(False)

        # (optional) Sets whether Spin Rewriter should automatically convert line-breaks to HTML tags.
        spinrewriter_api.set_use_html_linebreaks(False)
        text=self.textEdit.toPlainText().strip()
        result = spinrewriter_api.get_unique_variation(text)
        if result:
                self.textEdit_2.append(result['response'])
                msg = QMessageBox()
                msg.setWindowTitle("Paraphrasing Tool")
                msg.setText("Paraphrased Succesfully")
                msg.setIcon(QMessageBox.Information)
                x = msg.exec_()
        else:
                msg = QMessageBox()
                msg.setWindowTitle("Paraphrasing Tool")
                msg.setText("Error While Paraphrasing this text")
                msg.setIcon(QMessageBox.Critical)
                x = msg.exec_()

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(834, 423)
        MainWindow.setStyleSheet("background-color: #272743")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.seperator_summary = QtWidgets.QFrame(self.centralwidget)
        self.seperator_summary.setGeometry(QtCore.QRect(160, 0, 21, 441))
        self.seperator_summary.setStyleSheet("width:70px")
        self.seperator_summary.setFrameShape(QtWidgets.QFrame.VLine)
        self.seperator_summary.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.seperator_summary.setObjectName("seperator_summary")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 280, 161, 41))
        self.label_3.setStyleSheet("font-size:15pt;\n"
"color:rgb(255, 255, 253);\n"
"font: SMILEN;")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(40, 320, 71, 20))
        self.label_4.setStyleSheet("font-size:15pt;\n"
"color:rgb(255, 255, 253);\n"
"font: SMILEN;")
        self.label_4.setObjectName("label_4")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(180, 0, 591, 31))
        self.label.setStyleSheet("font-size:15pt;\n"
"color:rgb(255, 255, 253);\n"
"font: SMILEN;")
        self.label.setObjectName("label")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(180, 40, 531, 161))
        self.textEdit.setStyleSheet("background-color:white;")
        self.textEdit.setObjectName("textEdit")
        self.textEdit_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_2.setGeometry(QtCore.QRect(180, 230, 531, 181))
        self.textEdit_2.setStyleSheet("background-color:white;")
        self.textEdit_2.setObjectName("textEdit_2")
        self.textEdit_2.setReadOnly(True)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(720, 90, 101, 41))
        self.pushButton.setStyleSheet("background-color: rgb(186, 232, 232);\n"
"color: rgb(45, 102, 142);\n"
"font: SMILEN;\n"
"border-style:outset;\n"
"border-width:2px;\n"
"border-radius:10px;\n"
"font:bold 12px;\n"
"border-color:black;\n"
"padding:10px;")
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.Paraphrasingwork)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(0, 30, 151, 121))
        self.label_6.setStyleSheet("background-color: #272743")
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("LM.png"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(20, 190, 101, 81))
        self.label_7.setStyleSheet("background-color: #272743")
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap("Paraphrase Sentence.png"))
        self.label_7.setScaledContents(True)
        self.label_7.setObjectName("label_7")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(180, 200, 271, 31))
        self.label_2.setStyleSheet("font-size:15pt;\n"
"color:rgb(255, 255, 253);\n"
"font: SMILEN;")
        self.label_2.setObjectName("label_2")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(720, 290, 111, 41))
        self.pushButton_2.setStyleSheet("background-color: rgb(186, 232, 232);\n"
"color: rgb(45, 102, 142);\n"
"font: SMILEN;\n"
"border-style:outset;\n"
"border-width:2px;\n"
"border-radius:10px;\n"
"font:bold 12px;\n"
"border-color:black;\n"
"padding:10px;")
        self.pushButton_2.setObjectName("pushButton_2")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "PARAPHRASE"))
        self.label_4.setText(_translate("MainWindow", "TEXT"))
        self.label.setText(_translate("MainWindow", "Write text here and click the button to Paraphrase it:"))
        self.textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8.25pt;\"><br /></p></body></html>"))
        self.textEdit.setPlaceholderText(_translate("MainWindow", "Write your sentence here.."))
        self.textEdit_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8.25pt;\"><br /></p></body></html>"))
        self.textEdit_2.setPlaceholderText(_translate("MainWindow", "Write your sentence here.."))
        self.pushButton.setText(_translate("MainWindow", "Paraphrase"))
        self.label_2.setText(_translate("MainWindow", "Paraphrased Text:"))
        self.pushButton_2.setText(_translate("MainWindow", "Go To HOME"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow3()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
